---
slug: mechaniQ_pw
filename: eco+mechaniQs_
title: mechaniQs
subtitle: muons
description: a reference for the quantum novel
author: Ecosteader & Company
published: 2020
uuid: 5ad335b8-6409-4c17-b73c-61dc09d6d8fb
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
